### ISSUE TITLE
Can you please open-source the website code you told in Kodular.

### ISSUE THREAD

**Issue by hrichiksite** [vknow360/DeepLink#2]
https://community.kodular.io/t/add-deep-link-support-in-app/75136/109

Hi, Your Extension is very good that makes impossible to possible.

You provided a website link i.e. https://deep-link.000webhostapp.com/

Can you please share the source code of that website?

It will help us share and increase our knowledge. :smiley:

**Comment by vknow360** [comment]
Hi @hrichiksite 
Sorry, I don't want to open-source my website.
You should contact <a href="https://github.com/jarlisson2">Jarlisson José</a> because shared the template with me.

**Comment by hrichiksite** [comment]
Hi @vknow360 I have contacted Jarlisson José as you told in the community. And he has replied me.

**Comment by vknow360** [comment]
So I am closing this issue.
